var words = ["06-nummer","1 aprilgrap", "10-eurobiljet", "11 julifeest","16-metergebied","20-eurobiljet","24 uurseconomie","2D-printer","3D-printer","4-4-2-systeem","5 meiherdenking","5 eurobiljet","65+-kaart","8 uurjournaal","A-grootakkoord","aaibaarheidsfactor","aanbetaling","aanbodbeleid","aandelenindex","aanlegplaats","aanlooptransformator","aardappel"
,"zadelrob","Duitser","hoekverbinding","Jelle Borsboom","Pieter Mantel","hondenbezitter","prairiepaard","natuuronderzoek","elektronenflitser","vreemdetalenonderwijs","reformist","messteek","hotelrekening","stormwaarschuwingsdienst","ambulancier","beroepszaak","vlootoefening","girocheque","doodsoorzaak","podiuminstelling","raadsbesluit","premiekoopwoning"
,"noodrem","zuidoostkust","fade-out","beschildering","schildwacht","fontein","stuurstoel","museumbezoek","eclecticus","boventiteling","profijtbeginsel","muurkrant","automobielsector","abcdefghijklmnopqrstuvwxyz","qwertyuiopasdfghjklzxcvbnm","bewaarloon","werkcollege","priemgetal","uitzonderingsmaatregel","baggerlaars","tuinslang","probleemstelling"
,"blazerssectie","springbalk","radioloog","lentefeest","roman","asfaltweg","binnenzijde","crimineel","boskabouter","bosjesman","takkenwijf","heteluchtballon","borstbeeld","marmot","raamovereenkomst","kloosterzuster","huisgod","treinconducteur","pelmolen","neurotransmitter","muziektheater","pijlstaartvlinder","PVC-buis","vaargeul","duimschroef","seincode"
,"priesterfeest","tournee","boonkruid","boudweg","moordwapen","justitiebegroting","hoofdinspecteur","studievereniging","hematoloog","luitenant-generaal","commandoactie","Gastendoekje","bitterbal","xylofoon","gewetenszaak","democratiseringsproces","driekoningenbrood","zonneklep","dignitaris","rugpand","scharnier","afwerkplek","slagperk","gokker","steen"
,"wolfsangel","paperbackuitgave","Jannes de Keijser","cougar","Nidollo","Marijn vie die Bie","popcornmachine","bioscoopfilm","vaatwasser","telnetcommando","blikopener","uraniumsplijtingsreactie","trojaans paard","blender","bartap","frisdrankfontein","schoolbord","lesboek","muziekinstrument","driekwartsmaat","samengestelde maatsoort","dwarsfluit","G-sleutel"
,"trampoline","cirkelzaag","schuurpapiersorteermachine","schooltas","e-book","ansichtkaart","lampenkap","linoleumvloer","tube tandpasta","grootmoeders' receptenboek","beeldhouwwerk","encryptiemethode","voordeursleutel","trapleuning","wereldkaart","webpagina","brandalarm","rookmelder","moestuin","voetbalplaatje","stroopwafel","trollybuschauffeur","przewalskipaard"
,"Deutschlehrar","wandschildering","ijzerzaag","penceel","schildersezel","paard","koe","varken","eend","kip","bij","konijn","hamster","leguaan","cobra","boa constrictor","schaap","vuilnisbak","brandslang","klapdeur","driekwart broek","Dominique Moret","bounty-chocoladereep","palmboom","chipszak","aanhalingsteken","muzieknoot","tramrail","bovenleiding"
,"radiogolf","Superromain"];
var word = words[Math.floor(Math.random()*words.length)];
document.getElementById("text").innerHTML = "je bent zelf een " + word;